---
fixtures:
  repositories:
    stdlib:
      ref: "4.18.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    phpmyadmin:
      ref: "origin/master"
      repo: "https://github.com/justicel/puppet-phpmyadmin"
    mysql:
      ref: "3.11.0"
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
    staging:
      ref: "v2.2.0"
      repo: "https://github.com/voxpupuli/puppet-staging"
  symlinks:
    vision_mysql: '#{source_dir}'
