---
fixtures:
    repositories:
        phpmyadmin:
          ref: "origin/master"
          repo: "https://github.com/justicel/puppet-phpmyadmin"
        mysql:
          ref: "3.10.0"
          repo: "https://github.com/puppetlabs/puppetlabs-mysql"
        staging:
          ref: "v2.0.1"
          repo: "https://github.com/voxpupuli/puppet-staging"
        stdlib:
          ref: "4.12.0"
          repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    symlinks:
        vision_mysql: '#{source_dir}'
