---
fixtures:
  repositories:
    stdlib:
      ref: "4.24.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    mysql:
      ref: "8.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
  symlinks:
    vision_mysql: '#{source_dir}'
